<?php

namespace AppBundle\Repository;

/**
 * carnet_adresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carnet_adresseRepository extends \Doctrine\ORM\EntityRepository
{
}
